### ISSUE TITLE
Can the hashie dependency be relaxed?

### ISSUE THREAD

**Issue by monfresh** [berkshelf/varia_model#13]
Hi, I'm trying to install a gem which requires hashie >= 3.2, but I can't because varia_model is locking it at < 3.0.0. It looks like varia_model had an incompatibility with hashie > 3.0 at one point, but perhaps that can be addressed in a way other than locking the dependency to an old version?

Thanks!

**Comment by jgrevich** [comment]
:+1: me too!

**Comment by lamont-granquist** [comment]
its < 4.0.0 now so it looks like this got done
